#!/usr/bin/env python3

import click
import hat


@click.group()
def santa():
    pass


@santa.command()
@click.argument('names', nargs=-1)
def add(names):
    for name in names:
        click.echo('Added %s to the hat!' % name)
        hat.add(name)


@santa.command()
def list():
    names = hat.get_undrawn_users()
    click.echo("Undrawn users: ")
    for name in names:
        click.echo('{}'.format(name))


@santa.command()
@click.option('--name')
def draw(name):
    drawn_name = hat.assign(name)
    click.echo('{} drew {} from the hat!'.format(name, drawn_name))

if __name__ == '__main__':
    santa()
