#!/usr/bin/env python3

import click
import hat


@click.group()
def santa():
    pass


@santa.command()
@click.argument('names', nargs=-1)
def add(names):
    for name in names:
        click.echo('Added %s to the hat!' % name)
        hat.add(name)


@santa.command()
@click.option('--name/-n')
def draw(name):
    drawn_name = hat.remove(name)
    click.echo('%s drew %s from the hat!' % name, drawn_name)

if __name__ == '__main__':
    santa()
